### ISSUE TITLE
please provide a clean default configuration 

### ISSUE THREAD

**Issue by DavidePatria** [thibthib18/ros-nvim#5]
I have been using the plugin for a while, and I have realised that my config wasn't up to date when I opened the readme and saw major changes in the configuration.
unfortunately I found some errors in the configuration and I would ask if you could kindly provide a clean configuration that can be simply copied and pasted, because as of right now it doesn't work.

I got the default to work by setting the shortcuts and nothing more, because when I tried adding a setup function I couldn't figure out how to correct.
first error (although small) I found is
```
use { 'thibthib18/ros-nvim', config=function()
  require 'ros-nvim'.setup({})
}
```
lacking and **end** for the function.

then in the setup function
`map("n", "<c-k>", vim_utils.open_terminal_with_format_cmd_entry("rosnode kill %s"))`
`vim_util` isn't specified. I tried using `vim.utils.open_terminal_with_format_cmd_entry` but it didn't work at first and want to dig too much since you already have a working configuration with these fixed.

also, thank you for the great plugin, the echo thing in the picker is awesome and really helpful

**Comment by thibthib18** [comment]
Hi, thanks for the feedback and for catching this. I updated the documentation with the correct code in latest master.

This `vim_utils` module is actually the one from this plugin. So here the missing part was to require it  before calling the setup function:
```lua
local vim_utils = require "ros-nvim.vim-utils"   --   <--- This line here got added
require 'ros-nvim'.setup {
    -- .... 
node_picker_mappings = function(map)   --  Here nothing changes
       map("n", "<c-k>", vim_utils.open_terminal_with_format_cmd_entry("rosnode kill %s"))
   -- ..... 
```

I also noticed another typo or unclarity: that module is also the one for the `open_terminal_method` setting. To open a terminal in a new buffer (instead of a new split), one should set `open_terminal_method` to: 
```lua
open_terminal_method = function()
     require vim_utils.open_new_buffer()
end
```

**Comment by DavidePatria** [comment]
thank you very much for the fixes.
on a side note (we can move the discussion if you want, do you think that this plugin could me mde more versatile by making it source the workspace path rather than having to specify it manually? after all neovim is always started in a terminal which as already sourced a config file, so I think it would be doable

**Comment by thibthib18** [comment]
I'm not sure if I understand correctly, do you mean `catkin_ws_path` from the config?

A good part of this plugin is merely a wrapper around the various CLI tools from ROS (`rostopic`, `rosservice`, etc..), and as you might know, those do not care about the directory much.

This is only used for building (`ros-nvim.build.catkin_make`), as we need to set the directory in which to run the `catkin_make` command. For the rest it doesn't matter if you are in the specified workspace or not.

It is possible to detect if we are currently within a catkin workspace (e.g. using the `.catkin_workspace` file which serves this exact purpose). But again I'm not very confident I understood your issue 100%, so this might not be even required.

Note: I actually just discovered that the `catkin_ws_path` from the config wasn't even used, but instead using hardcoded `~/catkin_ws`, so that's fixed as well. Thanks for helping me discover more bugs :upside_down_face:

**Comment by DavidePatria** [comment]
Mi l my issue is related to the fact that I have different workspaces as ros package are sometimes tough to deal with (as you might know) therefore I wasn't sure that the make command (catkin build in my case) would work also in the workspaces not set in this plugin, but already solved that.

> Thanks for helping me discover more bugs 🙃

Given that I spend basically 40 hours a week in ros and neovim and that this plugin is extremely useful, given that now it also echoes topics, count on me for finding other bugs.

Thanks again

**Comment by thibthib18** [comment]
Happy to read that this already solved then. And more to know that this plugin is that useful to someone :smile: 
Just wanted to add: please do not hesitate to share if you have any ideas for this plugin that could improve your workflow. There is a good chance what could benefit you, could benefit me or others as well :smiley:

**Comment by DavidePatria** [comment]
well, if you ask: i was interested in creating a plugin that could source the `compile_commands.json` for clangd efficiently without having to manually move it. I don't know if you use clangd, but I would bet that you do.
usually the generate indice is in `$CATKIN_WS/build/$PACKAGE_NAME/compile_command.json`, but usually one has to move it manually. having a simple script to pass the path of this file to lspconfig to start clangd without having to copy it would be useful.
moreover it would be easy (if I knew how to do it) to prompt the user to recompile the package with the apposite flag that generates the indice.

so, do you use clangd?

**Comment by thibthib18** [comment]
Yes I do use clangd, and I also already have a function for compile command [in my dotfiles](https://github.com/thibthib18/dotfiles/blob/2f765819166ca5d2fe2a16fa27889ae9b51cbb2f/config/nvim/lua/thib/ros.lua#L14), though tbh I don't have to use it often.

I think this might be a bit too specific on one's workflow and config to include in this plugin. 

However, we could include some utilities to help you make this, like a function to detect if the current file or directory is within a catkin workspace.

You could then do it yourself with something like: 
- have an autocommand on some events like starting vim or opening a file (e.g. `VimEnter` or `BufAdd`)
- if you're in a catkin workspace, input the user whether to generate the compile commands with `vim.fn.input`
- restart clangd server and pass it the path to the freshly generated file (unfortunately i'm still using coc, so I can't help much with that last part, `LspRestart` or something?)

**Comment by DavidePatria** [comment]
I think a couple of utils to return the package name and to get the path would be really nice.
to source `compile_commands.json` it would just be matter of concatenating the two
